sudo: false
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - ln -s .env.test .env
script:
  - yarn run lint
  - yarn test
  - yarn run cover
  - yarn run codecov
