sudo: false
language: node_js
node_js:
  - "8"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add doughsay/greenkeeper-lockfile#fix-yarn
install:
  - yarn install
  - ln -s .env.test .env
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn cover
  - yarn codecov
after_script:
  - greenkeeper-lockfile-upload
